from homework4.homework4_for import *
from homework4.homework4_boolen import *
from homework4.homework4_list import *
from homework4.homework4_change_types import *
from homework4.homework4_condition import *
from homework4.homework4_dictionary import *
from homework4.homework4_string import *
from homework4.homework4_variable import *
from homework4.homework4_while import *
